// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: chat/v1/messages.proto

package chatv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SenderId      int64                  `protobuf:"varint,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	RecipientId   int64                  `protobuf:"varint,3,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_chat_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_chat_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Message) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *Message) GetRecipientId() int64 {
	if x != nil {
		return x.RecipientId
	}
	return 0
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Message) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Dialog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          *User                  `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	LastMessage   *Message               `protobuf:"bytes,2,opt,name=last_message,json=lastMessage,proto3" json:"last_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dialog) Reset() {
	*x = Dialog{}
	mi := &file_chat_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dialog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dialog) ProtoMessage() {}

func (x *Dialog) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dialog.ProtoReflect.Descriptor instead.
func (*Dialog) Descriptor() ([]byte, []int) {
	return file_chat_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *Dialog) GetPeer() *User {
	if x != nil {
		return x.Peer
	}
	return nil
}

func (x *Dialog) GetLastMessage() *Message {
	if x != nil {
		return x.LastMessage
	}
	return nil
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecipientId   int64                  `protobuf:"varint,1,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_chat_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_chat_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *SendMessageRequest) GetRecipientId() int64 {
	if x != nil {
		return x.RecipientId
	}
	return 0
}

func (x *SendMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_chat_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_chat_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *SendMessageResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type ListMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        int64                  `protobuf:"varint,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	BeforeId      *int64                 `protobuf:"varint,2,opt,name=before_id,json=beforeId,proto3,oneof" json:"before_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesRequest) Reset() {
	*x = ListMessagesRequest{}
	mi := &file_chat_v1_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesRequest) ProtoMessage() {}

func (x *ListMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListMessagesRequest) Descriptor() ([]byte, []int) {
	return file_chat_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *ListMessagesRequest) GetPeerId() int64 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

func (x *ListMessagesRequest) GetBeforeId() int64 {
	if x != nil && x.BeforeId != nil {
		return *x.BeforeId
	}
	return 0
}

func (x *ListMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListMessagesResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Messages []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	// не задан, если старше сообщений нет
	NextBeforeId  *int64 `protobuf:"varint,2,opt,name=next_before_id,json=nextBeforeId,proto3,oneof" json:"next_before_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesResponse) Reset() {
	*x = ListMessagesResponse{}
	mi := &file_chat_v1_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesResponse) ProtoMessage() {}

func (x *ListMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListMessagesResponse) Descriptor() ([]byte, []int) {
	return file_chat_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *ListMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ListMessagesResponse) GetNextBeforeId() int64 {
	if x != nil && x.NextBeforeId != nil {
		return *x.NextBeforeId
	}
	return 0
}

type ListDialogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDialogsRequest) Reset() {
	*x = ListDialogsRequest{}
	mi := &file_chat_v1_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDialogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDialogsRequest) ProtoMessage() {}

func (x *ListDialogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDialogsRequest.ProtoReflect.Descriptor instead.
func (*ListDialogsRequest) Descriptor() ([]byte, []int) {
	return file_chat_v1_messages_proto_rawDescGZIP(), []int{6}
}

func (x *ListDialogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListDialogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dialogs       []*Dialog              `protobuf:"bytes,1,rep,name=dialogs,proto3" json:"dialogs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDialogsResponse) Reset() {
	*x = ListDialogsResponse{}
	mi := &file_chat_v1_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDialogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDialogsResponse) ProtoMessage() {}

func (x *ListDialogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDialogsResponse.ProtoReflect.Descriptor instead.
func (*ListDialogsResponse) Descriptor() ([]byte, []int) {
	return file_chat_v1_messages_proto_rawDescGZIP(), []int{7}
}

func (x *ListDialogsResponse) GetDialogs() []*Dialog {
	if x != nil {
		return x.Dialogs
	}
	return nil
}

var File_chat_v1_messages_proto protoreflect.FileDescriptor

const file_chat_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x16chat/v1/messages.proto\x12\achat.v1\x1a\x12chat/v1/user.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa8\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\x03R\bsenderId\x12!\n" +
	"\frecipient_id\x18\x03 \x01(\x03R\vrecipientId\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"`\n" +
	"\x06Dialog\x12!\n" +
	"\x04peer\x18\x01 \x01(\v2\r.chat.v1.UserR\x04peer\x123\n" +
	"\flast_message\x18\x02 \x01(\v2\x10.chat.v1.MessageR\vlastMessage\"K\n" +
	"\x12SendMessageRequest\x12!\n" +
	"\frecipient_id\x18\x01 \x01(\x03R\vrecipientId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"A\n" +
	"\x13SendMessageResponse\x12*\n" +
	"\amessage\x18\x01 \x01(\v2\x10.chat.v1.MessageR\amessage\"t\n" +
	"\x13ListMessagesRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\x03R\x06peerId\x12 \n" +
	"\tbefore_id\x18\x02 \x01(\x03H\x00R\bbeforeId\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limitB\f\n" +
	"\n" +
	"_before_id\"\x82\x01\n" +
	"\x14ListMessagesResponse\x12,\n" +
	"\bmessages\x18\x01 \x03(\v2\x10.chat.v1.MessageR\bmessages\x12)\n" +
	"\x0enext_before_id\x18\x02 \x01(\x03H\x00R\fnextBeforeId\x88\x01\x01B\x11\n" +
	"\x0f_next_before_id\"*\n" +
	"\x12ListDialogsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"@\n" +
	"\x13ListDialogsResponse\x12)\n" +
	"\adialogs\x18\x01 \x03(\v2\x0f.chat.v1.DialogR\adialogs2\xd4\x02\n" +
	"\x0fMessagesService\x12e\n" +
	"\vSendMessage\x12\x1b.chat.v1.SendMessageRequest\x1a\x1c.chat.v1.SendMessageResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/messages\x12w\n" +
	"\fListMessages\x12\x1c.chat.v1.ListMessagesRequest\x1a\x1d.chat.v1.ListMessagesResponse\"*\x82\xd3\xe4\x93\x02$\x12\"/api/v1/dialogs/{peer_id}/messages\x12a\n" +
	"\vListDialogs\x12\x1b.chat.v1.ListDialogsRequest\x1a\x1c.chat.v1.ListDialogsResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/v1/dialogsB4Z2github.com/Rics69/rics-chat/pkg/api/chat/v1;chatv1b\x06proto3"

var (
	file_chat_v1_messages_proto_rawDescOnce sync.Once
	file_chat_v1_messages_proto_rawDescData []byte
)

func file_chat_v1_messages_proto_rawDescGZIP() []byte {
	file_chat_v1_messages_proto_rawDescOnce.Do(func() {
		file_chat_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_v1_messages_proto_rawDesc), len(file_chat_v1_messages_proto_rawDesc)))
	})
	return file_chat_v1_messages_proto_rawDescData
}

var file_chat_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_chat_v1_messages_proto_goTypes = []any{
	(*Message)(nil),               // 0: chat.v1.Message
	(*Dialog)(nil),                // 1: chat.v1.Dialog
	(*SendMessageRequest)(nil),    // 2: chat.v1.SendMessageRequest
	(*SendMessageResponse)(nil),   // 3: chat.v1.SendMessageResponse
	(*ListMessagesRequest)(nil),   // 4: chat.v1.ListMessagesRequest
	(*ListMessagesResponse)(nil),  // 5: chat.v1.ListMessagesResponse
	(*ListDialogsRequest)(nil),    // 6: chat.v1.ListDialogsRequest
	(*ListDialogsResponse)(nil),   // 7: chat.v1.ListDialogsResponse
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
	(*User)(nil),                  // 9: chat.v1.User
}
var file_chat_v1_messages_proto_depIdxs = []int32{
	8, // 0: chat.v1.Message.created_at:type_name -> google.protobuf.Timestamp
	9, // 1: chat.v1.Dialog.peer:type_name -> chat.v1.User
	0, // 2: chat.v1.Dialog.last_message:type_name -> chat.v1.Message
	0, // 3: chat.v1.SendMessageResponse.message:type_name -> chat.v1.Message
	0, // 4: chat.v1.ListMessagesResponse.messages:type_name -> chat.v1.Message
	1, // 5: chat.v1.ListDialogsResponse.dialogs:type_name -> chat.v1.Dialog
	2, // 6: chat.v1.MessagesService.SendMessage:input_type -> chat.v1.SendMessageRequest
	4, // 7: chat.v1.MessagesService.ListMessages:input_type -> chat.v1.ListMessagesRequest
	6, // 8: chat.v1.MessagesService.ListDialogs:input_type -> chat.v1.ListDialogsRequest
	3, // 9: chat.v1.MessagesService.SendMessage:output_type -> chat.v1.SendMessageResponse
	5, // 10: chat.v1.MessagesService.ListMessages:output_type -> chat.v1.ListMessagesResponse
	7, // 11: chat.v1.MessagesService.ListDialogs:output_type -> chat.v1.ListDialogsResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_chat_v1_messages_proto_init() }
func file_chat_v1_messages_proto_init() {
	if File_chat_v1_messages_proto != nil {
		return
	}
	file_chat_v1_user_proto_init()
	file_chat_v1_messages_proto_msgTypes[4].OneofWrappers = []any{}
	file_chat_v1_messages_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_v1_messages_proto_rawDesc), len(file_chat_v1_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_v1_messages_proto_goTypes,
		DependencyIndexes: file_chat_v1_messages_proto_depIdxs,
		MessageInfos:      file_chat_v1_messages_proto_msgTypes,
	}.Build()
	File_chat_v1_messages_proto = out.File
	file_chat_v1_messages_proto_goTypes = nil
	file_chat_v1_messages_proto_depIdxs = nil
}
