// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: chat/v1/users.proto

package chatv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeRequest) Reset() {
	*x = GetMeRequest{}
	mi := &file_chat_v1_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeRequest) ProtoMessage() {}

func (x *GetMeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeRequest.ProtoReflect.Descriptor instead.
func (*GetMeRequest) Descriptor() ([]byte, []int) {
	return file_chat_v1_users_proto_rawDescGZIP(), []int{0}
}

type GetMeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeResponse) Reset() {
	*x = GetMeResponse{}
	mi := &file_chat_v1_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeResponse) ProtoMessage() {}

func (x *GetMeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeResponse.ProtoReflect.Descriptor instead.
func (*GetMeResponse) Descriptor() ([]byte, []int) {
	return file_chat_v1_users_proto_rawDescGZIP(), []int{1}
}

func (x *GetMeResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type SearchUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersRequest) Reset() {
	*x = SearchUsersRequest{}
	mi := &file_chat_v1_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersRequest) ProtoMessage() {}

func (x *SearchUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersRequest.ProtoReflect.Descriptor instead.
func (*SearchUsersRequest) Descriptor() ([]byte, []int) {
	return file_chat_v1_users_proto_rawDescGZIP(), []int{2}
}

func (x *SearchUsersRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchUsersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersResponse) Reset() {
	*x = SearchUsersResponse{}
	mi := &file_chat_v1_users_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersResponse) ProtoMessage() {}

func (x *SearchUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_users_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersResponse.ProtoReflect.Descriptor instead.
func (*SearchUsersResponse) Descriptor() ([]byte, []int) {
	return file_chat_v1_users_proto_rawDescGZIP(), []int{3}
}

func (x *SearchUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_chat_v1_users_proto protoreflect.FileDescriptor

const file_chat_v1_users_proto_rawDesc = "" +
	"\n" +
	"\x13chat/v1/users.proto\x12\achat.v1\x1a\x12chat/v1/user.proto\x1a\x1cgoogle/api/annotations.proto\"\x0e\n" +
	"\fGetMeRequest\"2\n" +
	"\rGetMeResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.chat.v1.UserR\x04user\"@\n" +
	"\x12SearchUsersRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\":\n" +
	"\x13SearchUsersResponse\x12#\n" +
	"\x05users\x18\x01 \x03(\v2\r.chat.v1.UserR\x05users2\xc8\x01\n" +
	"\fUsersService\x12P\n" +
	"\x05GetMe\x12\x15.chat.v1.GetMeRequest\x1a\x16.chat.v1.GetMeResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/v1/users/me\x12f\n" +
	"\vSearchUsers\x12\x1b.chat.v1.SearchUsersRequest\x1a\x1c.chat.v1.SearchUsersResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/users/searchB4Z2github.com/Rics69/rics-chat/pkg/api/chat/v1;chatv1b\x06proto3"

var (
	file_chat_v1_users_proto_rawDescOnce sync.Once
	file_chat_v1_users_proto_rawDescData []byte
)

func file_chat_v1_users_proto_rawDescGZIP() []byte {
	file_chat_v1_users_proto_rawDescOnce.Do(func() {
		file_chat_v1_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_v1_users_proto_rawDesc), len(file_chat_v1_users_proto_rawDesc)))
	})
	return file_chat_v1_users_proto_rawDescData
}

var file_chat_v1_users_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_chat_v1_users_proto_goTypes = []any{
	(*GetMeRequest)(nil),        // 0: chat.v1.GetMeRequest
	(*GetMeResponse)(nil),       // 1: chat.v1.GetMeResponse
	(*SearchUsersRequest)(nil),  // 2: chat.v1.SearchUsersRequest
	(*SearchUsersResponse)(nil), // 3: chat.v1.SearchUsersResponse
	(*User)(nil),                // 4: chat.v1.User
}
var file_chat_v1_users_proto_depIdxs = []int32{
	4, // 0: chat.v1.GetMeResponse.user:type_name -> chat.v1.User
	4, // 1: chat.v1.SearchUsersResponse.users:type_name -> chat.v1.User
	0, // 2: chat.v1.UsersService.GetMe:input_type -> chat.v1.GetMeRequest
	2, // 3: chat.v1.UsersService.SearchUsers:input_type -> chat.v1.SearchUsersRequest
	1, // 4: chat.v1.UsersService.GetMe:output_type -> chat.v1.GetMeResponse
	3, // 5: chat.v1.UsersService.SearchUsers:output_type -> chat.v1.SearchUsersResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_chat_v1_users_proto_init() }
func file_chat_v1_users_proto_init() {
	if File_chat_v1_users_proto != nil {
		return
	}
	file_chat_v1_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_v1_users_proto_rawDesc), len(file_chat_v1_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_v1_users_proto_goTypes,
		DependencyIndexes: file_chat_v1_users_proto_depIdxs,
		MessageInfos:      file_chat_v1_users_proto_msgTypes,
	}.Build()
	File_chat_v1_users_proto = out.File
	file_chat_v1_users_proto_goTypes = nil
	file_chat_v1_users_proto_depIdxs = nil
}
